### ISSUE TITLE
Make fails on Ubuntu Studio 17.10

### ISSUE THREAD

**Issue by BN701** [a-n-t-h-o-n-y/CPPurses#1]
Hi, 

I've been following the build instructions in the readme. The two git operations succeeded, then I had to install GTest and that seemed to be OK, too, but now make is failing and I'm stuck for an idea:

`barry@lightbulb-s2:~/Code Blocks Projects/CPPurses/build$ make
Scanning dependencies of target cppurses
[  0%] Building CXX object CMakeFiles/cppurses.dir/src/system/child_event.cpp.o
c++: error: unrecognized command line option ‘-ferror-limit=10’
CMakeFiles/cppurses.dir/build.make:62: recipe for target 'CMakeFiles/cppurses.dir/src/system/child_event.cpp.o' failed
make[2]: *** [CMakeFiles/cppurses.dir/src/system/child_event.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cppurses.dir/all' failed
make[1]: *** [CMakeFiles/cppurses.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

Do you have any suggestions?

Thanks,

B

**Comment by a-n-t-h-o-n-y** [comment]
Looks like it was using Clang specific compiler options, I have updated the CMakeLists.txt to fix this, it should be working now. Let me know if you have any other issues.

**Comment by BN701** [comment]
Thanks, I'll have a look and let you know if there's still a problem. B
