### ISSUE TITLE
Usage on repl.it

### ISSUE THREAD

**Issue by LoganDark** [a-n-t-h-o-n-y/CPPurses#10]
Your library looks like something where this would be possible, so here goes...

On https://repl.it, in order to use a library, I have to find a way to `#include` it. Is there a way that this library can be `#include`d? I can't use CMake or anything like that.

**Comment by a-n-t-h-o-n-y** [comment]
I'm not very familiar with repl.it, but it looks like they do not support C++14 yet, and this library requires it. Also this is not a header only library so you'd have to compile it locally and import the library archive and headers into repl.it, and then link to that library which I'm not sure is possible with what repl.it gives you.

**Comment by LoganDark** [comment]
Yeah, honestly it did look like this might've been a header-only library with a ton of includes. Turns out it's not. Sorry for bothering
