### ISSUE TITLE
undefined reference to `cppurses::Tree::set_head(cppurses::Widget*)'

### ISSUE THREAD

**Issue by qjnr** [a-n-t-h-o-n-y/CPPurses#15]
Whenever I try to compile my program, I get this error:
```
undefined reference to `cppurses::Tree::set_head(cppurses::Widget*)'
```
My CMake file:
```
cmake_minimum_required(VERSION 2.8)

project(CPPursesTest)
add_executable(${PROJECT_NAME} "main.cpp")

target_link_libraries(${PROJECT_NAME} -lcppurses -lncurses -pthread)
```

Can anyone please help me? Thanks in advance!

**Comment by sheldonth** [comment]
Try cloning the repo and adding
```
add_subdirectory(CPPurses)
target_link_libraries(${PROJET_NAME} cppurses)
```
That way you don't need to worry about which version is installed in /usr/lib - the library will be built as a dependency to your `{PROJECT_NAME}` target
