### ISSUE TITLE
List initialization in the library examples

### ISSUE THREAD

**Issue by sheldonth** [a-n-t-h-o-n-y/CPPurses#16]
In your code you often have the convention where a class reference member is list initialized with the return value of *_layout->make_child<Widget>()

but doing so with a function parameter list seems to cause a compiler error.

```class Application : public Vertical_layout
{
private:
    Textbox_base& textBoxBase{this->make_child<Textbox_base>("This is my textbox")}; // works
//    Textbox_base& textBoxBase(this->make_child<Textbox_base>("This is my textbox")); // compile err
};
```
I'm having trouble figuring out where your code makes the distinction for the list initialization?

**Comment by a-n-t-h-o-n-y** [comment]
The compiler can't parse a member initializer with parenthesis, it believes it is a function declaration. You either have to use brace or equal initializers, [see here](https://en.cppreference.com/w/cpp/language/data_members#Member_initialization). I think that's what's happening here.

**Comment by sheldonth** [comment]
Ah, always more to learn. Thank you.
