### ISSUE TITLE
ALLOW_DUPLICATE_CUSTOM_TARGETS global property kills Xcode IDE

### ISSUE THREAD

**Issue by sheldonth** [a-n-t-h-o-n-y/CPPurses#24]
Because the ALLOW_DUPLICATE_CUSTOM_TARGETS global property flag is set, we get into a situation where certain CMake generators are unhappy.

Cmake generation fails with an error message

```
-- Configuring done
CMake Error: This project has enabled the ALLOW_DUPLICATE_CUSTOM_TARGETS global property.  The "Xcode" generator does not support duplicate custom targets.  Consider using a Makefiles generator or fix the project to not use duplicate target names.
```

I'm not sure exactly what it is that that accomplishes but I wonder if there's a way it can be turned off (At least on Apple systems)

**Comment by a-n-t-h-o-n-y** [comment]
This is a hack I put in to have multiple custom targets that aren't really needed. I should have a fix out in just a bit.

**Comment by a-n-t-h-o-n-y** [comment]
a9fc08faa563d4e267bdd8a99bd49398da2db888 should fix it, on master branch

**Comment by sheldonth** [comment]
Awesome. Thanks.
