### ISSUE TITLE
Error when compiling program using current master brach

### ISSUE THREAD

**Issue by MuteCodemonkey** [a-n-t-h-o-n-y/CPPurses#27]
The error occurs when I try to compile any program using(or even just including) the current master branch version of cppurses and reads as follows:
`usr/bin/ld: /usr/local/lib/libcppurses.a(event_loop.cpp.o): in function 'std::thread::thread<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<cppurses::Event_loop::run_async()::{lambda()#1}> >, int>::_Async_state_impl(std::tuple<cppurses::Event_loop::run_async()::{lambda()#1}>&&)::{lambda()#1}, , void>(std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<cppurses::Event_loop::run_async()::{lambda()#1}> >, int>::_Async_state_impl(std::tuple<cppurses::Event_loop::run_async()::{lambda()#1}>&&)::{lambda()#1}&&)':
event_loop.cpp:(.text+0x2061): undefined reference to 'pthread_create'
/usr/bin/ld: /usr/local/lib/libcppurses.a(output.cpp.o): in function '(anonymous namespace)::put_as_wchar(cppurses::Glyph const&)':
output.cpp:(.text+0x30f): undefined reference to 'setcchar'
/usr/bin/ld: output.cpp:(.text+0x32a): undefined reference to 'wadd_wchnstr'
collect2: error: ld returned 1 exit status`

Now this could just be because it didn't install correctly but I still believe it should brought to to your attention if it was not an installation problem.

OS: Ubuntu 19.04
arch: x64

**Comment by a-n-t-h-o-n-y** [comment]
If you are trying to link to an installed version of the library, and not building the library within the project, you will need to link to the following libraries: `cppurses ncurses pthread`.

If you are building the project as a dependency within your application, and you are using cmake, then you can just `target_link_libraries(my_app cppurses)` and it should automatically link to the above mentioned libraries for you.

"Using the Library" section in README.md covers this in a bit more detail.
I'm guessing this is the problem because the above errors state there are undefined references to `pthread_create` and `wadd_wchnstr` which are defined when you link in ncurses and pthread

**Comment by MuteCodemonkey** [comment]
well that is where my confusion is coming from as they are linked properly(as far as I am aware)
here is an example of the code I used to test it:

CMakeLists.txt:
cmake_minimum_required(VERSION 3.2)
add_executable(main main.cpp)
target_compile_features(main PRIVATE cxx_std_17)
target_link_libraries(main cppurses ncurses pthread)

main.cpp:`
#include <cppurses/cppurses.hpp>
using namespace cppurses;
int main() {
    System sys;
    Glyph_string greeting{"Hello, World!", Attribute::Underline};
    Textbox tb{greeting};
    tb.brush.set_background(Color::Dark_blue);
    tb.brush.set_foreground(Color::Light_blue);
    tb.border.enable();
    return (sys.run(tb));
}
`

sorry for the poor formatting I'm not used to github

**Comment by a-n-t-h-o-n-y** [comment]
I can't reproduce this on my system(Arch Linux), I'll try a bit later on virtual box with Ubuntu 19

**Comment by a-n-t-h-o-n-y** [comment]
Looks like it needs to be linked with `ncursesw` instead of `ncurses` if your system has the wide char version of ncurses installed. I've updated the documentation.

I can't reproduce the pthread linker error on a fresh install of Ubuntu 19.04 x64, maybe check that pthread is installed correctly.

**Comment by MuteCodemonkey** [comment]
using ncursew fixed both issues, thx
