### ISSUE TITLE
 error Compiling : wadd_wchnstr’ has not been declared

### ISSUE THREAD

**Issue by savimportweb** [a-n-t-h-o-n-y/CPPurses#3]
Hello,

I'd love to use your library for some personal projects, and also play your curses chess game over ssh

i use a rapsberry pi 3 for my developpement (with latest stretch rapsbian/debian)
i cloned CPPurses repository, just like in your instructions, i had to setup google tests lib and ncurses to get to this step on my deb box,

at the step "make " i encouter a compiling error,(after cmake ..), the full output of make is :  
``root@raspberrypi:/home/pi/Downloads/HTMLPAGES/CPPurses/build# make
[  1%] Building CXX object CMakeFiles/cppurses.dir/src/system/ncurses_event_listener.cpp.o
[  3%] Building CXX object CMakeFiles/cppurses.dir/src/system/on_tree_event.cpp.o
[  3%] Building CXX object CMakeFiles/cppurses.dir/src/system/paint_event.cpp.o
[  4%] Building CXX object CMakeFiles/cppurses.dir/src/system/resize_event.cpp.o
[  6%] Building CXX object CMakeFiles/cppurses.dir/src/system/show_event.cpp.o
[  7%] Building CXX object CMakeFiles/cppurses.dir/src/system/system.cpp.o
[  9%] Building CXX object CMakeFiles/cppurses.dir/src/system/shortcuts.cpp.o
[ 11%] Building CXX object CMakeFiles/cppurses.dir/src/painter/ncurses_paint_engine.cpp.o
/home/pi/Downloads/HTMLPAGES/CPPurses/src/painter/ncurses_paint_engine.cpp: In member function ‘void cppurses::detail::NCurses_paint_engine::put_glyph(const cppurses::Glyph&)’:
/home/pi/Downloads/HTMLPAGES/CPPurses/src/painter/ncurses_paint_engine.cpp:123:5: error: ‘::wadd_wchnstr’ has not been declared
     ::wadd_wchnstr(::stdscr, &image, 1);
     ^~
CMakeFiles/cppurses.dir/build.make:686: recipe for target 'CMakeFiles/cppurses.dir/src/painter/ncurses_paint_engine.cpp.o' failed
make[2]: *** [CMakeFiles/cppurses.dir/src/painter/ncurses_paint_engine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cppurses.dir/all' failed
make[1]: *** [CMakeFiles/cppurses.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
root@raspberrypi:/home/pi/Downloads/HTMLPAGES/CPPurses/build#

**Comment by a-n-t-h-o-n-y** [comment]
Thanks for your interest in the project! What version of ncurses are you using? and what compiler and version?

**Comment by savimportweb** [comment]
hey again, thanks for your response,

for ncurses, i uses those packages/versions :

pi@raspberrypi:~ $  dpkg -l '*ncurses*' | grep '^ii'
ii  libncurses5:armhf      6.0+20161126-1+deb9u2 armhf        shared libraries for terminal handling
ii  libncurses5-dev:armhf  6.0+20161126-1+deb9u2 armhf        developer's libraries for ncurses
ii  libncursesw5:armhf     6.0+20161126-1+deb9u2 armhf        shared libraries for terminal handling (wide character support)
ii  libncursesw5-dev:armhf 6.0+20161126-1+deb9u2 armhf        developer's libraries for ncursesw
ii  ncurses-base           6.0+20161126-1+deb9u2 all          basic terminal type definitions
ii  ncurses-bin            6.0+20161126-1+deb9u2 armhf        terminal-related programs and man pages
ii  ncurses-term           6.0+20161126-1+deb9u2 all          additional terminal type definitions


as for the compiler, i use CMAKE if i'm not wrong, the output of -version is : 

pi@raspberrypi:~/Downloads/HTMLPAGES/CPPurses/build $ cmake -version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by a-n-t-h-o-n-y** [comment]
Try out the following commit on branch issue_3:
125f4f12f17f1450ae6f35c58a28997b2ae9548b

Let me know if it works for you and I'll merge it into the master branch.
Just a note, unless your version of ncurses has wchar_t support built in,the library will be limited to a subset of displayable characters, in the case of the chess demo it will display letters rather than glyphs of the pieces.

**Comment by savimportweb** [comment]
it works nicely !

got no glyph though :( , still playable ! Thanks !

**Comment by a-n-t-h-o-n-y** [comment]
Glad it works!
I went ahead and updated the build system so it can find the wchar_t ncurses library if it exists. It looks like your system does have the library, so you should be able to get the glyphs if you fetch the latest commit on the master branch and build again.
f7cf4d7da9bc1b148d721dcb066bd24cb3c608d0
