### ISSUE TITLE
"Feature" request: Better documentation and code examples

### ISSUE THREAD

**Issue by Deneuki** [a-n-t-h-o-n-y/CPPurses#30]
I know that this is still mostly an early WIP project with an unstable API, but I think it would still be nice to have some more code examples in the wiki to illustrate, incrementally, how certain features are implemented using this library. Yes, one could look in the code demos and the documentation, but this would still be nice to have. For example, see [how this unrelated library does it in their wiki](https://github.com/picoe/Eto/wiki/Tutorial-3-Table-Layout).

P.S. I quite like this project, and it's much less clunky than CDK, let alone directly using ncurses.

**Comment by Deneuki** [comment]
Ignore if this is already something that is already being addressed, or will be addressed once the API has stabilzed.

**Comment by Deneuki** [comment]
Not something that warrants an issue or feature request.

**Comment by a-n-t-h-o-n-y** [comment]
Hey, I think some documentation could really help out this project, at the moment it is mostly kept in my head, which is less than ideal. I don't have a whole lot of time at the moment to work on this, but it is definitely a high priority.
And thanks for the link, that's a great example. I've been trying to design a generic Table widget API so it might help me with that too.

**Comment by Deneuki** [comment]
Hello, a-n-t-h-o-n-y! I opened this "issue" because I quite like this project (much better than something like CDK), but didn't think that opening an issue would be appropriate, since you probably had this in mind anyway. But, in the meantime, I think piece-by-piece code samples could work, too. For example, a sample that demonstrates the use of one or two things instead of a full control gallery or toy program, for those who are lazy to read larger samples, and/or for people to learn CPPurses control by control.

**Comment by jon-harper** [comment]
Something like Qt’s widget samples? Small, independent samples illustrating
a few controls and usage of the library, which can then be included or
referenced in the docs, perhaps?

Jon

**Comment by Deneuki** [comment]
Yes, I was thinking of something like that. It's not entirely necessary, as some complete control galleries are pretty simply written, or written in a modular, control-by-control (or category-by-category) way, but I think this would be both easier to read and write, in terms of self-documenting code.
