### ISSUE TITLE
Aur package does not compile

### ISSUE THREAD

**Issue by mattilaa** [a-n-t-h-o-n-y/CPPurses#37]
Hi,

First of all, thanks for the great library! I'm utilizing it in my own c++ project and it feels great!

I use Arch Linux, and the Aur-package seems to be broken. I get error:

CMake Error at src/CMakeLists.txt:170 (export):
  export given target "optional" which is not built by this project.

I managed to build it manually by first building Optional library and installing it, removing references to "optional" from src/CMakeLists.txt then building and installing the Cppurses. The same issue is in the master build.

**Comment by a-n-t-h-o-n-y** [comment]
Thank for bringing that to my attention, it looks like the PKGBUILD file in the AUR is manually handling the git submodules and it ends up pulling in the wrong commits. I've sent a patch to the maintainer, I'll let you know if I get a response.
Glad you are getting use from the library!

**Comment by mattilaa** [comment]
The issue has been fixed, thanks! :)
