### ISSUE TITLE
Wide characters show garbled code

### ISSUE THREAD

**Issue by zhaoqibin** [a-n-t-h-o-n-y/CPPurses#38]
I see in the code border segments default is 
   /// Holds all 8 Segments that a Border is made up of.
    struct Segments {
        Segment north{L'─'};
        Segment south{L'─'};
        Segment east{L'│'};
        Segment west{L'│'};
        Segment north_west{L'┌'};
        Segment north_east{L'┐'};
        Segment south_west{L'└'};
![WeChat Work Screenshot_20200706151344](https://user-images.githubusercontent.com/4850767/86567660-4b763f00-bf9e-11ea-9b00-e466cb19d0dd.png)

        Segment south_east{L'┘'};

**Comment by zhaoqibin** [comment]
who can tell me why border is "^@"

**Comment by a-n-t-h-o-n-y** [comment]
Hey zhaoqibin,
Are you using the `master` branch or the `develop` branch?
What OS & version are you using?

Some ncurses implementations are missing wide character support, CPPurses does have a workaround built in for certain characters, but that doesn't seem to be working here, with the above info I might be able to figure out the source of the issue.

Thanks,
Anthony

**Comment by zhaoqibin** [comment]
@a-n-t-h-o-n-y 

Hey Anthony:
Thank your reply!  my machine OS is ubuntun18.04

I've solved this problem,
root cause: libcppurses.a linked libncurses.so , wide characters are not supported!
soultion: should install libncursesw.so instead of libncuses.so

Thank you again.

**Comment by zhaoqibin** [comment]
root cause: libcppurses.a linked libncurses.so , wide characters are not supported!
soultion: should install libncursesw.so instead of libncurses.so
