### ISSUE TITLE
Widget List incomplete implementation

### ISSUE THREAD

**Issue by zhaoqibin** [a-n-t-h-o-n-y/CPPurses#39]
Widget List is very useful 
this class is not fully implemented in CPPurses project

look at:
include/cppurses/widget/widgets/list.hpp.idk

Is anyone working on this class?

**Comment by a-n-t-h-o-n-y** [comment]
Hi,
I never quite figured out what the API for that class should be, it is removed in the `develop` branch. The way I would build a list of widgets now would be to have a vertical layout holding some kind of data display widget, maybe something like this:

```cpp
struct Data_display : cppurses::layout::Horizontal {
    using Display_t  = cppurses::Text_display;
    Display_t& name  = this->make_child<Display_t>("");
    Display_t& value = this->make_child<Display_t>("");
    
    Data_display() { this->height_policy.fixed(1); }
};

struct List : cppurses::layout::Vertical {
    std::vector<Data_display*> data;

    void add_item(std::string name, std::string value)
    {
        auto& item = this->make_child<Data_display>();
        item.name.set_contents(name);
        item.value.set_contents(value);
        data.push_back(&item);
    }
};
```
I haven't tested the above code, but hopefully that gets you on the right track.
