### ISSUE TITLE
Update documentation to point to how to install gtest.

### ISSUE THREAD

**Issue by ojmakke** [a-n-t-h-o-n-y/CPPurses#4]
While installing following instructions, one would get: 

CMake Error at /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY)

**Comment by a-n-t-h-o-n-y** [comment]
Google Test is no longer used in this library.
